language: node_js
node_js:
  - 8.5.0
script:
  - "npm run lint"
  - "npm run test"
deploy:
  provider: heroku
  api_key:
    secure: 9f7bf711-605d-495b-8b32-31ff54a26ac3
  app: adogtame-gps
  on:
    repo: chinataun/adogtame